[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Frame-Options = "DENY", X-XSS-Protection = "1; mode=block", Referrer-Policy = "strict-origin-when-cross-origin"}

[dev]
  framework = "vite"
  targetPort = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Cache-Control = "public, max-age=31536000"
